import { XMLParser } from 'fast-xml-parser';
import * as fs from 'fs-extra';
import { SanctionRecord, Address } from '../../shared/types';

function toArray(val: any): any[] {
  if (val === undefined || val === null) return [];
  return Array.isArray(val) ? val : [val];
}

export async function parseEUList(filePath: string): Promise<SanctionRecord[]> {
  console.log(`Parsing EU sanctions list from ${filePath}...`);
  const xmlContent = await fs.readFile(filePath, 'utf-8');
  
  const parser = new XMLParser({
    ignoreAttributes: false,
    parseAttributeValue: true,
    trimValues: true,
    removeNSPrefix: true, // Automatically strips namespace prefixes! E.g. fsd:export becomes export.
  });

  const parsed = parser.parse(xmlContent);
  // Root might be export or export/sanctionEntity
  const exportNode = parsed.export;
  const sanctionEntities = exportNode?.sanctionEntity;

  if (!sanctionEntities) {
    console.warn('No sanctionEntity found in EU XML file.');
    return [];
  }

  const entries = toArray(sanctionEntities);
  const records: SanctionRecord[] = [];

  for (const entry of entries) {
    const logicalId = entry['@_logicalId'] || entry.logicalId;
    if (!logicalId) continue;

    // Determine type (I = individual, E = entity, F = family, etc.)
    const subjectTypeCode = entry.subjectType?.['@_code'] || entry.subjectType?.code || '';
    let type: 'individual' | 'entity' | 'vessel' | 'aircraft' = 'entity';
    if (subjectTypeCode === 'I') {
      type = 'individual';
    }

    // Parse name aliases
    const nameAliases = toArray(entry.nameAlias);
    let primaryName = '';
    const aliases: string[] = [];

    for (const nameItem of nameAliases) {
      const isPrimary = nameItem['@_primary'] === true || nameItem['@_primary'] === 'true' || nameItem.primary === true;
      const whole = nameItem.wholeName || '';
      const first = nameItem.firstName || '';
      const last = nameItem.lastName || '';
      const constructed = whole ? whole : `${first} ${last}`.trim();

      if (!constructed) continue;

      if (isPrimary && !primaryName) {
        primaryName = constructed;
      } else {
        if (!aliases.includes(constructed)) {
          aliases.push(constructed);
        }
      }
    }

    // Fallback if no primary name is specified
    if (!primaryName && aliases.length > 0) {
      primaryName = aliases.shift()!;
    }
    if (!primaryName) {
      primaryName = 'Unknown Name';
    }

    // Parse addresses
    const addresses: Address[] = [];
    const rawAddresses = toArray(entry.address);
    for (const addr of rawAddresses) {
      const country = addr.countryDescription || addr.countryCode || addr.country || '';
      const street = addr.street || '';
      const city = addr.city || '';
      const zip = addr.zipcode || '';
      const fullParts = [street, city, zip, country].filter(Boolean);
      addresses.push({
        street: street || undefined,
        city: city || undefined,
        country: country || undefined,
        fullAddress: fullParts.join(', ') || undefined,
      });
    }

    // Parse birth dates and places
    const datesOfBirth: string[] = [];
    const placesOfBirth: string[] = [];
    const birthdates = toArray(entry.birthdate);
    for (const bd of birthdates) {
      if (bd.birthdate) {
        datesOfBirth.push(String(bd.birthdate));
      }
      const city = bd.city || '';
      const country = bd.countryDescription || bd.country || '';
      const pob = [city, country].filter(Boolean).join(', ');
      if (pob) {
        placesOfBirth.push(pob);
      }
    }

    // Parse citizenships
    const citizenships: string[] = [];
    const citizens = toArray(entry.citizenship);
    for (const cz of citizens) {
      const country = cz.countryDescription || cz.country || '';
      if (country && !citizenships.includes(country)) {
        citizenships.push(country);
      }
    }

    // Parse passport / identification documents
    const passports: string[] = [];
    const idDocs = toArray(entry.identificationDocument);
    for (const doc of idDocs) {
      const num = doc.number || '';
      const docType = doc.typeDescription || doc.type || '';
      const country = doc.issueCountry || '';
      if (num) {
        const detail = docType ? `${docType} ${num}${country ? ` (${country})` : ''}` : num;
        passports.push(detail);
      }
    }

    // Legal basis and regulation summary
    const sanctionReason = entry.regulationSummary?.numberTitle || entry.regulation?.numberTitle || '';
    const legalBasis = entry.regulationSummary?.publicationUrl || entry.regulation?.publicationUrl || '';

    records.push({
      id: `EU-${logicalId}`,
      source: 'EU',
      type,
      primaryName,
      aliases,
      searchNames: [], // Generated by uploader
      datesOfBirth: datesOfBirth.length > 0 ? datesOfBirth : undefined,
      placesOfBirth: placesOfBirth.length > 0 ? placesOfBirth : undefined,
      citizenships: citizenships.length > 0 ? citizenships : undefined,
      passports: passports.length > 0 ? passports : undefined,
      addresses: addresses.length > 0 ? addresses : undefined,
      sanctionReason: sanctionReason || undefined,
      legalBasis: legalBasis || undefined,
      rawSourceData: entry,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
  }

  console.log(`Parsed ${records.length} EU records.`);
  return records;
}
